/** Topic catalogue (all 30 assignments). */
export const TOPICS = {
  1: "FCFS CPU Scheduler",
  2: "SJF CPU Scheduler",
  3: "Priority Scheduling (Preemptive)",
  4: "Priority Scheduling (Non-Preemptive)",
  5: "Preemptive vs. Non-Preemptive Scheduling",
  6: "Process States",
  7: "Process Control Block (PCB)",
  8: "Context Switching",
  9: "IPC: Shared Memory Model",
  10: "IPC: Message Passing Model",
  11: "Direct Memory Access (DMA)",
  12: "Linker and Loader",
  13: "Deadlocks",
  14: "Virtual Memory and Paging",
  15: "Threading",
  16: "Parallelism",
  17: "Concurrency",
  18: "Multithreading Models",
  19: "When is Multithreading Beneficial?",
  20: "OS as a Bridge: Hardware and Software",
  21: "User Mode vs. Kernel Mode",
  22: "Interrupts",
  23: "lseek()",
  24: "fork()",
  25: "wait()",
  26: "exit()",
  27: "sleep()",
  28: "dup() and dup2()",
  29: "read()",
  30: "write()",
};

export const STATUSES = ["pending", "received", "broken", "approved"];
